[profile.default]
name = 'contracts-template'
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
evm_version = "shanghai"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
single_line_statement_blocks = "preserve" # can force either way
exclude = ['lib/']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
arbitrum-goerli = "${ARBITRUM_GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY_MAINNET}" }
arbitrum-goerli = { key = "${ETHERSCAN_KEY_ARBITRUM}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
